accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from .views import SignUp

app_name='accounts'

urlpatterns= [
    url(r'login/$',
    auth_views.LoginView.as_view(template_name='accounts/login.html'),
    name='login'),
    url(r'logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'signup/$',SignUp.as_view(),name='signup')
]

chat/urls.py
from django.urls import path
from . import views

# Defined namespace for use on all templates
app_name = 'chat'

urlpatterns = [
	path('', views.IndexView.as_view(), name = "index"),
	path('chat/<str:uuid>/', views.ChatRoomView.as_view(), name = "chatroom"),

	#AJAX paths
	path('ajax/users-list/', views.users_list, name = "users_list"),
	path('ajax/get-chat-url/', views.get_chat_url, name = "get_chat_url"),
	path('ajax/get-messages/<str:uuid>/', views.get_messages, name="get_messages")
]

serefe_backend/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    url(r'accounts/',include('accounts.urls',namespace='accounts')),
]

accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class Userdetail(auth.models.User,auth.models.PermissionsMixin):
    def __str__(self):
        return "@{}".format(self.username)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Userdetail

class UserCreateForm(UserCreationForm):
    phone_number=forms.CharField(required=True)
    location=forms.CharField(required=True)
    class Meta:
        model = Userdetail
        fields = ("username", "phone_number","location", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=True)
        user.phone_number = self.cleaned_data["phone_number"]
        user.location=self.cleaned_data["location"]
        if commit:
            user.save()
        return user
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        #assigning label for actual field
        self.fields['username'].label='Username'

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms
# Create your views here.

class SignUp(CreateView):
    form_class=forms.UserCreateForm
    success_url=reverse_lazy('login')
    template_name='accounts/signup.html'

accounts/templates/accounts/login.html
{% load static %}
<html>
<head>
	<title>Login V19</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
				<form class="login100-form validate-form" method="POST">
					<span class="login100-form-title p-b-33">
						Account Login
					</span>

					{%csrf_token%}
          {{ form }}

					<div class="container-login100-form-btn m-t-20">
						<button class="login100-form-btn">
							Sign in
						</button>
					</div>

					<div class="text-center p-t-45 p-b-4">
						<span class="txt1">
							Forgot
						</span>

						<a href="#" class="txt2 hov1">
							Username / Password?
						</a>
					</div>

					<div class="text-center">
						<span class="txt1">
							Create an account?
						</span>

						<a href="{% url 'accounts:signup' %}" class="txt2 hov1">
							Sign up
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>



<!--===============================================================================================-->
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/daterangepicker/moment.min.js"></script>
	<script src="vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="js/main.js"></script>
</body>

</html>

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{%load bootstrap3 %}

{%block content %}

<div class="container">
  <h1> Sign Up</h1>
  <form method="POST">
    {%csrf_token %}
    {%bootstrap_form form %}
    <input type="submit" value="Sign Up" class='btn btn-default'>

    </form>
  </div>
{% endblock %}